### ISSUE TITLE
Downloading files that requires Referer header

### ISSUE THREAD

**Issue by abelfn** [TachibanaGeneralLaboratories/download-navi#176]
what do you mean?

This still requires referer header

https://www.pixiv.net/en/artworks/83953383

**Comment by proninyaroslav** [comment]
I cannot verify this because this site is blocked for me for some reason. Why are you sure that the reason in `Referer`? The `Referer` header was implemented in a previous version and it works with sites that require it, for example https://dl.twrp.me/guacamole/twrp-installer-3.5.0_9-0-guacamole.zip. Can you provide a log of HTTP requests?

**Comment by proninyaroslav** [comment]
I don't know how to check it. In my country, this site is blocked, but when connected via Tor, the server itself blocks me and returns HTTP 403 in all browsers. If anyone has the opportunity to provide me a log with HTTP traffic (you can collect it with third-party utilities), then open it again.
