### ISSUE TITLE
[Double Request] make downloads with errors as resumable - update links for downloads. 

### ISSUE THREAD

**Issue by Albnu14** [TachibanaGeneralLaboratories/download-navi#39]
Hello there,
May I ask, is there any way to make the downloads that end with errors, resumable? Like adding a "resume" button to files that end with errors.
This is a second request related to the previous , is there any way to update link for already existing files?
I request these because most files I try to download end with an error, either because of bad connection or the site itself (since others don't seem to have any problems).

**Comment by proninyaroslav** [comment]
You can edit url in the Detail window. Also you can fully redownload in the Detail window. I think I’ll take the redownload option to another place.

**Comment by Albnu14** [comment]
Thanks for replying,
I'm not talking about redownloading, rather about resuming partially downloaded files that stopped downloading because of some problem with the internet,
The redownload option downloads the file from 0 to 100%, what I'm looking for is to download a file that stopped at 40% from 40% to 100%,
I'll test the next release and report any bug I see as soon as possible.
Thanks for your hard work :relaxed:

**Comment by proninyaroslav** [comment]
Interest Ask. By default, a failed download truncates the file size to zero so that it doesn't take up space.
About resuming partially downloaded files: in general, there should be no problems, I can add a "resume" button if the server supports partial loading.
I see no reason to resume downloading after changing the URL, since a person can mistakenly insert the URL of a completely different file, and this will lead to many problems, for example, we get a Frankenstein file that will contain parts of two different files.

**Comment by proninyaroslav** [comment]
I opened this issue as an improvement, I will make the resume button for the current url, in case an error occurs, the user may try to reconnect to the server.

**Comment by proninyaroslav** [comment]
Implemented 1dd5cd3. Also you should turn off "Delete file if an error occurs" in Storage settings.

**Comment by proninyaroslav** [comment]
Also I allowed resume downloads with error only manually, not by "Resume all" button and etc.
